# name: assert.async() handled after fail in other test
# command: ["qunit", "drooling-done.js"]

TAP version 13
not ok 1 Test A
  ---
  message: |+
    Died on test #2: this is an intentional error
        at /qunit/test/cli/fixtures/drooling-done.js:5:7
        at internal
  severity: failed
  stack: |
    Error: this is an intentional error
        at /qunit/test/cli/fixtures/drooling-done.js:8:9
  ...
ok 2 Test B
1..2
# pass 1
# skip 0
# todo 0
# fail 1

# exit code: 1

