# name: assert.async() handled again in other test
# command: ["qunit", "drooling-extra-done.js"]

TAP version 13
ok 1 Test A
not ok 2 Test B
  ---
  message: |+
    Died on test #2: Unexpected release of async pause during a different test.
    > Test: Test A [async #1]
        at /qunit/test/cli/fixtures/drooling-extra-done.js:13:7
        at internal
  severity: failed
  stack: |
    Error: Unexpected release of async pause during a different test.
    > Test: Test A [async #1]
  ...
1..2
# pass 1
# skip 0
# todo 0
# fail 1

# exit code: 1
